name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
        # Label used to access the service container
        postgres:
          image: postgres:12
          env:
            POSTGRES_USER: root
            POSTGRES_DB: simple_bank
            POSTGRES_PASSWORD: secret
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
